
services:
  app-host:
    build:
      context: .
      dockerfile: docker/main.Dockerfile
    container_name: main-container
    ports:
      - "8000:8000" # Expose port 8000 of app1 to port 8000 on the host
    environment:
      DB_PATH: "/code/db/main.db"
      RESULTS_PATH: "/code/results"
    networks:
      - app-network
    volumes:
      - volume-1:/aws_connections
      - volume-2:/aws_credentials
      - volume-3:/code/db

  steampipe-host:
    build:
      context: .
      dockerfile: docker/steampipe.Dockerfile
    container_name: steampipe-container
    networks:
      - app-network
    volumes:
      - volume-1:/home/andrew/.steampipe/config/
      - volume-2:/home/andrew/.aws/

networks:
  app-network:
    driver: bridge

volumes:
  volume-1:
  volume-2:
  volume-3: