---
Metadata:
  TemplateId: "arn:aws:cloudformation:ap-southeast-2:010928207640:generatedTemplate/1ed31660-c375-4cbe-bd60-931e84c43cd6"
Resources:
  IAMRole00ExternalSecurityAudit00m6xdP:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Delete"
    Properties:
      Path: "/"
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/ReadOnlyAccess"
      MaxSessionDuration: 3600
      RoleName: "External-Security-Audit"
      Description: "email AlignedSoftware@gmail.com for more information"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Condition:
            StringEquals:
              sts:ExternalId: "010928207640"
          Action: "sts:AssumeRole"
          Effect: "Allow"
          Principal:
            AWS: "arn:aws:iam::010928207640:root"
