name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.EC2_SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        if_key_exists: replace
    
    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
      run: |
        scp -r ./* $USER@$HOST:/home/admin/build
        ssh $USER@$HOST <<EOF
          cd /home/admin/build
          CONTAINER_ID=$(docker ps -aqf "name=simpliance")
          echo $CONTAINER_ID
          if [ -n "$CONTAINER_ID" ]; then
            docker stop $CONTAINER_ID
            docker rm $CONTAINER_ID
          fi
          docker build -t simpliance_image .
          docker run -d --name=simpliance -p 8000:8000 simpliance_image
        EOF