name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.EC2_SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        if_key_exists: replace
    
    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
      run: |
        scp -r ./* $USER@$HOST:/home/ubuntu/src
        ssh $USER@$HOST <<EOF
          cd /home/ubuntu/src
          python3 -m venv .env
          source .env/bin/activate
          pip3 install -r requirements.txt
          sudo systemctl restart fastapi-app
        EOF